### ISSUE TITLE
Pop a question when running login.py

### ISSUE THREAD

**Issue by lilianzhi0** [ECNUSR/ecnu_network_login#2]
ReferenceError: _PADCHAR is not defined

**Comment by CCjiahao** [comment]
一般是包的问题，一般来说var _PADCHAR = "="，可以在此添加：https://github.com/ECNUSR/ecnu_network_login/blob/master/utils/encryption.py#L37。
如果有兴趣将这部分JS代码替换成原生python代码的话，欢迎提PR~~，这样便可以永久规避这个问题，并且避免在无网络环境下安装“js2py”的窘境。

**Comment by lilianzhi0** [comment]
已解决，感谢。

**Comment by CCjiahao** [comment]
好的，最新的代码中也加上了var _PADCHAR = "="。当时直接copy的校园网的源码，不知道为啥少了这一行。
